### ISSUE TITLE
OneShot{Milli,Micro}I

### ISSUE THREAD

**Issue by biosbob** [em-foundation/zigem-dev#17]
Milestone: 

The `OneShot` abstraction needs to include usecs as well as msecs. This is particularly important for `Poller.pause()`, where need an "inline sleep" for (say) 50us....

With no urgent need to preserve backward compatibility, we have several alternative ways to expose the APIs:

* create a parallel `OneShotMicroI` abstraction
* consolidate around a single `OneShotI` abstraction with two methods
* consolidate around a single `OneShotI` abstraction, but with usecs as the unit

In practice, a usec-resolution timer with 24-bits of range can handle intervals up to 16 seconds &ndash; more than enough time for our intended use.  Legacy 8-bit/16-bit MCUs would prefer having **two** abstractions/methods for flexibility, however.

**Comment by biosbob** [comment]
the second alternative seems like the best balance....  i work towards a PR for review

**Comment by gcohler** [comment]
Fixed by #20
